version: "3.7"
services:
  app:
    build:
      args:
        user: dieisson
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: money-control
    container_name: money-control-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - money-control

  nginx:
    image: nginx:alpine
    container_name: money-control-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - money-control

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mcdb
      MYSQL_USER: mcuser
      MYSQL_PASSWORD: mcpass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  adminer:
      depends_on:
        - db
      image: adminer
      restart: always
      ports:
        - 8888:8080

networks:
  money-control:
    driver: bridge

volumes:
  db:
