version: "3.7"
services:
  app:
    build:
      args:
        user: dieisson
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: money-control
    container_name: money-control-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - money-control

  nginx:
    image: nginx:alpine
    container_name: money-control-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - money-control

networks:
  money-control:
    driver: bridge
